name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Install packages
        run: npm ci

      - name: Building
        run: npm run build
      
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Build Machine
          message: 'Build Machine Works'
